## 2021-03-08 R Intro
## Source: http://leg.ufpr.br/~silvia/R2001/contents.html

## Store values
x <- 3
y <- x
x <- 2

## Vectors
v <- 1:10
v
y <- c( v, 2, 3,4)


z <- c(1:3, 1:4)
z

## Define a (finite) sequence with a given start, end, and step size
seq(1, 10, .5)
seq(10, 1, -1)
seq(10, 1, -2)
seq(3, 87)

## Vector Indexes
v <- 1:10
v+2 -> v
v[1]

v[1:3]
v[100000]
v[-1] # nice way to remove an element from a vector
v[-3] # works for any index number :)
v
v==4
v == 4
v=3
v
w=rev(v) # rev() reverses the vector
w

## Managing variables 
ls()
rm(x)
ls()

## Useful functions
summary(v)


## Loading csv
x = read.csv("foo.csv")
x[1]
x[2,3]

## Plotting
x <- 1:20
y <- x**3
plot(x,y)
lines(x,y)
points(rev(x),y,pch=3)

points(x,y,pch="$")

lines(x,y,lwd=4) # thicc line
lines(rev(x),y,lty=2) # dash line
lines(rev(x),y,lwd=5,lty=2) # thicc dash line


## Print plot to a file
dev.print(file="gme-stock-price.ps")
plot(x,y,xlab="Monke hold banana long tim",ylab="Rocket Up", pch="$")
dev.off()





## For loops
for (year in 2010:2015){
  print(paste("The year is", year))
}



## Automate plot creation
v=1:10

for (item in v)
{
plot(x,y,xlab="Monke hold banana long tim",ylab="Rocket Up", pch="$")
dev.print(file=sprintf("gme-stonk-%s.ps", item)) 
dev.off()
}

## In the above, sprintf can accomodate more variables. Use the notation sprintf(“%s_%s.csv”,var1, var2)
a
b=2
sprintf("%s...%s",a,b)
sprintf("%s_%s",a,b)

## Exit R
q()




## First steps: Connecting the pipeline (2021-03-09)
##
## First load simulator.fasl and execute-consensus-jc.fasl. Then from the
## scripts directory, run the command:
##
## (mapcar #'try-various-recombination-rates '(160000 80000 40000 20000 10000) '(2 4 8 16 32))
##
## This generates fives files, located in the data/ directory:
##
##   consensus-jc-N10000-L32-F0.1.csv
##   consensus-jc-N20000-L16-F0.1.csv
##   consensus-jc-N40000-L8-F0.1.csv
##   consensus-jc-N80000-L4-F0.1.csv
##   consensus-jc-N160000-L2-F0.1.csv
##   
## Each of such file has 32 rows, one row for every possible assignment of
## recombination rate 0 or 1 to the five populations in the species tree (for
## example (1 0 0 0 0) or (0 1 1 0 1) or whatever). In particular, each row is
## generated by simulating N=10000,20000,40000,...,160000 ancestral
## recombination graphs for loci of size L=32,16,...,4,2 respectively. Loci of
## shorter length require more samples to get an accurate estimate of the
## inference probabilities. I haven't checked if this scaling is sufficient, but
## I'm short on time right now (2021-03-09) and I'm still figuring the pipeline out.
##
## Next, load up the R environment. To load these csv files as dataframes into
## R, run the commands

x1 = read.csv("consensus-jc-N160000-L2-F0.1.csv",header=TRUE)
x2 = read.csv("consensus-jc-N80000-L4-F0.1.csv)",header=TRUE)
x3 = read.csv("consensus-jc-N40000-L8-F0.1.csv",header=TRUE)
x4 = read.csv("consensus-jc-N20000-L16-F0.1.csv",header=TRUE)
x5 = read.csv("consensus-jc-N10000-L32-F0.1.csv",header=TRUE)

## (The header=TRUE is not required, since this is the default.)
##
## Now we want to analyze the data and make some pictures. Useful source:
## https://www.stat.berkeley.edu/~s133/R-4a.html
##
## The estimated probability of inferring the true species topology:

summary(x1[1])
summary(x2[1])
summary(x3[1])
summary(x4[1])
summary(x5[1])

## and we can do things like this, which doesn't look like much

plot(1:32,x5$P.ab)

## and this, which seems to suggest we better increase our samples

boxplot(x1$P.ab, x2$P.ab, x3$P.ab, x4$P.ab, x5$P.ab)
